### ISSUE TITLE
MMB List

### ISSUE THREAD

**Issue by tbergq** [kiwicom/mobile#519]
[Zeplin](https://zpl.io/29NRrBz)

## Subtasks: 
- [x] Create image
- [x] Create layout on mobile
- [x] Create layout on tablet
- [x] Pull to refresh (current app has this)
- [x] Future & past trips
- [x] Grayscale past trips image
- [x] Sort bookings in GraphQL response
- [x] Navigate to booking on click

## Questions
- What about the hotels tab? Shall we ignore it, will we get design for it?
- Icons?
- Is it correct that there are 3 statuses -> Refunded, Closed, Confirmed?
- Design only shows how confirmed should look, what about the other statuses?
- On iPad, should bookings be scrollable, or should they break on to newline if there are more than 3?

**Comment by MRTNKCR** [comment]
Let's add some description, it will help our tester to do the QA properly.

The list of booking contains photo of the destination, booking status, BID, origin, destination, departure date and number of passengers. 

![img_7779](https://user-images.githubusercontent.com/7661448/39575252-1df0ee36-4eda-11e8-8be3-c8296ea6c74a.PNG)

Also, there can be 3 different types of booking, represented by i different symbol in the center of the card:

- One-way trip:

![img_7780](https://user-images.githubusercontent.com/7661448/39575338-67744ac6-4eda-11e8-9f40-ca825a9072f1.PNG)

- Return trip:

![img_7780 2](https://user-images.githubusercontent.com/7661448/39575349-73e3eea6-4eda-11e8-9751-1a0fa03a1165.PNG)

 - Multicity trip:
![img_7780 3](https://user-images.githubusercontent.com/7661448/39575380-8ec52f3c-4eda-11e8-921b-ea342200ca60.PNG)

**Comment by mrtnzlml** [comment]
Can be closed after this: https://github.com/kiwicom/graphql/pull/205
