### ISSUE TITLE
Passengers screen

### ISSUE THREAD

**Issue by tbergq** [kiwicom/mobile#523]
[Zeplin](https://zpl.io/bro6drX)
![img](https://cdn.zeplin.io/59a9818fe86dfd4f75f2c142/screens/90EA22B2-A941-49B1-ADE6-6BB3C477E69B.png)

## tasks
- [x] pull to refresh
- [x] Passenger details
- [x] Visa information
- [x] Bags
- [x] Contact information
- [x] Visa disclaimer info
- [ ] Add personal items to bags
- [ ] Add Stroller to bags

## Questions
- Icons?
- The visa requirement, seems to be html from server? What about styling?

**Comment by MRTNKCR** [comment]
The Visa info is requested from VisaHQ, I'm trying to obtain more details.

The icons should be pulled from Fontastic.

**Comment by MRTNKCR** [comment]
Ok, so the visa info should be a part of the response to "travel_info" request. Can you please check it @tbergq ?

**Comment by MRTNKCR** [comment]
Ok, here we go: https://booking.kiwi.wiki/wiki/#/features/visa

**Comment by MRTNKCR** [comment]
Ok, here we go: https://booking.kiwi.wiki/wiki/#/features/visa

**Comment by MRTNKCR** [comment]
@tbergq ok, i'll ask about the styling for the response

**Comment by MRTNKCR** [comment]
I checked with Pavel Zak again. His response: we turn the HTML into string (drop html tags except of `<b>` and style this string according to design.

**Comment by MRTNKCR** [comment]
Ok, please use this API

**Comment by tbergq** [comment]
It looks like this info is already in the booking response. 
```
"travel_info": {
  "<passengerId>": {
	"0": {
	  "visa": {
	    "status": "critical|notice|ok",
	  }
	}
  }
}
```

**Comment by mrtnzlml** [comment]
@tbergq Is this all we need in order to do this scene completely?

**Comment by tbergq** [comment]
I do think so yes

**Comment by tbergq** [comment]
critical = visa required
notice = visa may be required
ok = no visa

**Comment by tbergq** [comment]
@MRTNKCR I still need some help, 

there is one visa status pr. segment(leg). So, Say I fly from Prague -> New York -> Oslo. I might need visa the US, I do not need visa for Norway.

Do we display one status for each leg? (does not look like they do that now 🤷‍♂️ )
Do we display the most severe?

**Comment by MRTNKCR** [comment]
On it ✌️

**Comment by MRTNKCR** [comment]
Ok, here it is. There is a list of countries requiring Visa: 
![image uploaded from ios 2](https://user-images.githubusercontent.com/7661448/40221140-d927f74c-5a7b-11e8-9aed-7bb435914813.png)

**Comment by tbergq** [comment]
So for the case, I fly from a->b->c->d->e. 

Visa is required for b and c, might be required for e, and no visa for d. 

What do I show? 
```
-----------------------------
|Visa required in:          |
|b                          |
|c                          |
-----------------------------

-----------------------------
|Visa might be required in: |
|e                          |
-----------------------------
```

**Comment by tbergq** [comment]
Current api for bags are buggy and of limited use, they are porting to new endpoint, which booking-backend says ETA = ASAP 🙈 . I say we wait with the bags task until new endpoint is released.

**Comment by tbergq** [comment]
Closing, we should create new issues if we ever touch MMB again
